spring:
  application:
    name: jaz-s27281-nbp
  datasource:
    url: jdbc:h2:mem:nbp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

nbp:
  api:
    base-url: https://api.nbp.pl/api

server:
  port: 8081
